#!/bin/bash
set -o nounset
set -o errexit

PYSYRUP_DIR=~/Projects/pysyrup/

python $PYSYRUP_DIR/compile_syrup.py ../settings.json

WAFFLELIB_DIR=~/Projects/waffle-lib/python/
PYTHONPATH=$PYTHONPATH:$WAFFLELIB_DIR
python $WAFFLELIB_DIR/wafflecore/test.py
